export const destinationRegionMap: Record<string, number> = {
    // Miền Bắc
    'Hà Nội': 1,
    'Hải Phòng': 1,
    'Quảng Ninh': 1,
    'Bắc Giang': 1,
    'Bắc Kạn': 1,
    'Bắc Ninh': 1,
    'Cao Bằng': 1,
    'Điện Biên': 1,
    'Hà Giang': 1,
    'Hà Nam': 1,
    'Hòa Bình': 1,
    'Hưng Yên': 1,
    'Lai Châu': 1,
    'Lạng Sơn': 1,
    'Lào Cai': 1,
    'Nam Định': 1,
    'Ninh Bình': 1,
    'Phú Thọ': 1,
    'Sơn La': 1,
    'Thái Bình': 1,
    'Thái Nguyên': 1,
    'Tuyên Quang': 1,
    'Vĩnh Phúc': 1,
    'Yên Bái': 1,
  
    // Miền Trung
    'Đà Nẵng': 2,
    'Thanh Hóa': 2,
    'Nghệ An': 2,
    'Hà Tĩnh': 2,
    'Quảng Bình': 2,
    'Quảng Trị': 2,
    'Huế': 2,
    'Quảng Nam': 2,
    'Quảng Ngãi': 2,
    'Bình Định': 2,
    'Phú Yên': 2,
    'Khánh Hòa': 2,
    'Ninh Thuận': 2,
    'Bình Thuận': 2,
    'Kon Tum': 2,
    'Gia Lai': 2,
    'Đắk Lắk': 2,
    'Đắk Nông': 2,
    'Lâm Đồng': 2,
  
    // Miền Nam
    'TP. Hồ Chí Minh': 3,
    'Bình Dương': 3,
    'Bình Phước': 3,
    'Tây Ninh': 3,
    'Bà Rịa - Vũng Tàu': 3,
    'Đồng Nai': 3,
    'Long An': 3,
    'Tiền Giang': 3,
    'Bến Tre': 3,
    'Trà Vinh': 3,
    'Vĩnh Long': 3,
    'Cần Thơ': 3,
    'Hậu Giang': 3,
    'Sóc Trăng': 3,
    'An Giang': 3,
    'Đồng Tháp': 3,
    'Kiên Giang': 3,
    'Bạc Liêu': 3,
    'Cà Mau': 3,
  };
  